
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace Hotfix.Common.Data.Config
{
    /// <summary>
    /// 全局配置表
    /// </summary>
    public partial class TbGlobalConfig
    {
        

        private readonly GlobalConfig _data;

        public TbGlobalConfig(ByteBuf _buf)
        {
            int n = _buf.ReadSize();
            if (n != 1) throw new SerializationException("table mode=one, but size != 1");
            _data = GlobalConfig.DeserializeGlobalConfig(_buf);
        }


        /// <summary>
        /// 背包上限
        /// </summary>
        public int BagMax => _data.BagMax;
        
        public void ResolveRef(Tables tables)
        {
            _data.ResolveRef(tables);
        }
    }

}
