
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace Hotfix.Common.Data.Example
{
    /// <summary>
    /// 进阶例子
    /// </summary>
    public partial class TbExampleExtendStruct
    {
        
        private readonly System.Collections.Generic.Dictionary<int, ExtendStruct> _dataMap;
        private readonly System.Collections.Generic.List<ExtendStruct> _dataList;
        
        public TbExampleExtendStruct(ByteBuf _buf)
        {
            _dataMap = new System.Collections.Generic.Dictionary<int, ExtendStruct>(0x0004);
            _dataList = new System.Collections.Generic.List<ExtendStruct>(0x0004);
            
            for(int n = _buf.ReadSize() ; n > 0 ; --n)
            {
                ExtendStruct _v;
                _v = ExtendStruct.DeserializeExtendStruct(_buf);
                _dataList.Add(_v);
                _dataMap.Add(_v.Id, _v);
            }
        }

        public System.Collections.Generic.Dictionary<int, ExtendStruct> DataMap => _dataMap;
        public System.Collections.Generic.List<ExtendStruct> DataList => _dataList;

        public ExtendStruct GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
        public ExtendStruct Get(int key) => _dataMap[key];
        public ExtendStruct this[int key] => _dataMap[key];

        public void ResolveRef(Tables tables)
        {
            foreach(var _v in _dataList)
            {
                _v.ResolveRef(tables);
            }
        }

    }

}
