
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace Hotfix.Common.Data.L10n
{ 
    public enum LanguageType
    {
        /// <summary>
        /// 中文
        /// </summary>
        CN = 1,
        /// <summary>
        /// 英文
        /// </summary>
        EN = 2,
    }

} 

